//! Configuration for the auto-organization pipeline.
//!
//! Auto-organization is opt-in per file and reversible. The [`OrgConfig`] holds
//! the global toggles (whether the generative LLM tier is enabled, which
//! requires an AI provider) while per-file enablement is a flag on each job.

use serde::{Deserialize, Serialize};

use crate::auto_org::rules::RuleSet;

/// Global auto-organization settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrgConfig {
    /// Whether to run the deterministic classic-ML pipeline at all.
    pub enabled: bool,
    /// Whether the generative LLM filename tier is allowed. Requires an AI
    /// provider to be configured; ignored (and forced offline) when disabled.
    pub generative_enabled: bool,
    /// Similarity threshold (Jaccard) above which a document is a duplicate.
    pub dedup_threshold: f64,
    /// Shingle size for MinHash de-duplication.
    pub shingle_k: usize,
    /// Number of clusters for k-means (overridden by `default_k` when 0).
    pub cluster_k: usize,
    /// Placement rules + filename template.
    pub rules: RuleSet,
}

impl Default for OrgConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            generative_enabled: false,
            dedup_threshold: 0.85,
            shingle_k: 3,
            cluster_k: 0,
            rules: RuleSet {
                placement: Vec::new(),
                fallback_path: Some("/inbox".to_owned()),
                filename_template: RuleSet::default_template(),
            },
        }
    }
}

/// The result of organizing a single document: everything the caller needs to
/// apply (or show for approval).
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrgPlan {
    pub document_id: String,
    /// Predicted tags (emergent + reused), ordered by confidence.
    pub tags: Vec<String>,
    /// Deterministically resolved hierarchy path, if any.
    pub suggested_path: Option<String>,
    /// Renamed filename (title), if the pipeline produced one.
    pub suggested_title: Option<String>,
    /// Id of an existing document this one is a duplicate of, if any.
    pub is_duplicate_of: Option<String>,
    /// Aggregate confidence in `[0, 1]`.
    pub confidence: f64,
    /// Whether the filename came from a generative provider vs. a template.
    pub filename_source: FilenameSource,
}

/// Where a suggested title came from.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum FilenameSource {
    /// Deterministic template over keywords/metadata.
    #[default]
    Template,
    /// Generated by a generative LLM (only when a provider is enabled).
    Generative,
}
