// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The connection state of a given peer as observed by the local node.
///
/// Mirrored in Dart so the UI can render connection status without bridging a
/// richer (non-serializable) libp2p object.
enum ConnectionState {
  /// A peer was discovered (e.g. via mDNS) but no connection is established
  /// yet, or a previously open connection has closed.
  disconnected,

  /// A transport connection to the peer is currently established.
  connected,
}
