//! `docer-core` — the Rust engine behind the docer app.
//!
//! The crate is split into two parts:
//!
//! * [`api`] — the small, stable surface exposed to Flutter through
//!   `flutter_rust_bridge`. This is the *only* place `#[frb]` attributes appear.
//! * The feature modules below — the actual domain logic. They are currently
//!   **interfaces only** (traits + data types); implementations land in later
//!   tasks, one module at a time.
//!
//! ## Feature modules (interfaces only)
//!
//! * [`domain`]    — shared document/tag/hierarchy model.
//! * [`storage`]   — local document storage (metadata index + blob store).
//! * [`taxonomy`]  — tagging and folder hierarchy operations.
//! * [`search`]    — full-text and semantic search.
//! * [`ai`]        — pluggable AI providers.
//! * [`auto_org`]  — AI auto-organization pipeline.
//! * [`assistant`] — chat assistant with document references.
//! * [`sync`]      — peer-to-peer file sync with conflict resolution.

pub mod api;
pub mod domain;
pub mod storage;
pub mod taxonomy;
pub mod search;
pub mod ai;
pub mod auto_org;
pub mod assistant;
pub mod sync;

// Generated by `flutter_rust_bridge_codegen generate`. Do not edit.
mod frb_generated;
