//! `docean-core` — the Rust engine behind the docean app.
//!
//! The crate is split into two parts:
//!
//! * [`api`] — the small, stable surface exposed to Flutter through
//!   `flutter_rust_bridge`. This is the *only* place `#[frb]` attributes appear.
//! * The feature modules below — the actual domain logic, each implemented and
//!   exposed to Dart through a thin `api` facade.
//!
//! ## Feature modules
//!
//! * [`domain`]    — shared document/tag/hierarchy model.
//! * [`storage`]   — local document storage (metadata index + blob store).
//! * [`ingest`]    — file ingestion pipeline (hash, copy, text extraction).
//! * [`taxonomy`]  — tagging and folder hierarchy operations.
//! * [`search`]    — full-text and semantic search.
//! * [`ai`]        — pluggable AI providers.
//! * [`auto_org`]  — automatic document organization (classic-ML first, deterministic).
//! * [`assistant`] — chat assistant with document references.
//! * [`sync`]      — peer-to-peer file sync with conflict resolution.

pub mod api;
pub mod domain;
pub mod ingest;
pub mod library_fs;
pub mod storage;
pub mod taxonomy;
pub mod search;
pub mod ai;
pub mod auto_org;
pub mod assistant;
pub mod net;
pub mod sync;
pub mod library_sync;

// Generated by `flutter_rust_bridge_codegen generate`. Do not edit.
mod frb_generated;
