// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How text generation should shape its output.
enum GenerateMode {
  /// A short, deterministic answer (used by the classifier and assistant).
  answer,

  /// A longer, more creative completion.
  creative,

  /// A terse heading/label (used by the auto-organizer).
  summary,
}
