// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Extracted/ingested textual content for a document.
///
/// Kept separate from [`Document`] metadata so that raw binary documents can be
/// stored without text, and so multiple extraction passes (OCR, re-parse) can
/// update the text without touching the immutable content hash.
class Content {
  /// The document this text belongs to.
  final String documentId;

  /// Plain-text content extracted from the document.
  final String text;

  /// A short extractor identifier, e.g. `"pdf"`, `"ocr"`, `"markdown"`.
  final String source;

  const Content({
    required this.documentId,
    required this.text,
    required this.source,
  });

  @override
  int get hashCode => documentId.hashCode ^ text.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Content &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          text == other.text &&
          source == other.source;
}

/// A document as tracked by the system.
///
/// Raw bytes live in the blob store (see [`crate::storage`]); this struct is the
/// indexed metadata record.
class Document {
  final String id;
  final String? parentId;
  final NodeKind kind;
  final String title;
  final String mimeType;
  final BigInt sizeBytes;

  /// SHA-256 of the raw bytes, used for de-duplication and integrity checks.
  final String checksumSha256;
  final List<String> tags;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  /// Extensible key/value metadata (EXIF, OCR language, source URL, ...).
  ///
  /// A `HashMap` rather than `BTreeMap` because `flutter_rust_bridge` can
  /// translate `HashMap<K, V>` → Dart `Map<K, V>` but not `BTreeMap`.
  final Map<String, String> extra;

  const Document({
    required this.id,
    this.parentId,
    required this.kind,
    required this.title,
    required this.mimeType,
    required this.sizeBytes,
    required this.checksumSha256,
    required this.tags,
    required this.createdAtMs,
    required this.updatedAtMs,
    required this.extra,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parentId.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      checksumSha256.hashCode ^
      tags.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Document &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parentId == other.parentId &&
          kind == other.kind &&
          title == other.title &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          checksumSha256 == other.checksumSha256 &&
          tags == other.tags &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          extra == other.extra;
}

/// A directed parent/child edge used to assemble the folder hierarchy.
class HierarchyLink {
  final String parentId;
  final String childId;

  /// Ordinal position of the child among its siblings.
  final int position;

  const HierarchyLink({
    required this.parentId,
    required this.childId,
    required this.position,
  });

  @override
  int get hashCode => parentId.hashCode ^ childId.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HierarchyLink &&
          runtimeType == other.runtimeType &&
          parentId == other.parentId &&
          childId == other.childId &&
          position == other.position;
}

/// A hierarchy path, e.g. `/work/invoices/2026`.
///
/// A path is an entity independent of any single document: a document may be
/// reachable through *many* paths (each a [`PathAssignment`] edge), and a path
/// may contain many documents. This is a many-to-many relationship mirroring
/// filesystem hard links / multiple virtual folders.
class HierarchyPath {
  /// Canonical, `/`-separated path with a leading slash. Unique in storage.
  final String path;

  const HierarchyPath({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HierarchyPath &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

/// Whether a hierarchy node is a leaf document or a folder/collection.
enum NodeKind { document, folder }

/// A member edge of the many-to-many relationship between documents and paths.
///
/// One document ↔ many paths, and one path ↔ many documents.
class PathAssignment {
  final String documentId;
  final String path;

  /// Ordinal position of the document among the path's members.
  final int position;

  const PathAssignment({
    required this.documentId,
    required this.path,
    required this.position,
  });

  @override
  int get hashCode => documentId.hashCode ^ path.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathAssignment &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          path == other.path &&
          position == other.position;
}

/// A user-defined tag. Tags may be nested (e.g. `receipts/2026`) via [`Tag::parent`].
class Tag {
  final String name;
  final String? parent;
  final String? color;

  const Tag({required this.name, this.parent, this.color});

  @override
  int get hashCode => name.hashCode ^ parent.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          parent == other.parent &&
          color == other.color;
}
