// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Extracted/ingested textual content for a document.
///
/// Kept separate from [`Document`] metadata so that raw binary documents can be
/// stored without text, and so multiple extraction passes (OCR, re-parse) can
/// update the text without touching the immutable content hash.
class Content {
  /// The document this text belongs to.
  final String documentId;

  /// Plain-text content extracted from the document.
  final String text;

  /// A short extractor identifier, e.g. `"pdf"`, `"ocr"`, `"markdown"`.
  final String source;

  const Content({
    required this.documentId,
    required this.text,
    required this.source,
  });

  @override
  int get hashCode => documentId.hashCode ^ text.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Content &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          text == other.text &&
          source == other.source;
}

/// A document as tracked by the system.
///
/// Raw bytes live in the blob store (see [`crate::storage`]); this struct is the
/// indexed metadata record.
class Document {
  final String id;
  final String? parentId;
  final NodeKind kind;
  final String title;
  final String mimeType;
  final BigInt sizeBytes;

  /// SHA-256 of the raw bytes, used for de-duplication and integrity checks.
  final String checksumSha256;
  final List<String> tags;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  /// Extensible key/value metadata (EXIF, OCR language, source URL, ...).
  ///
  /// A `HashMap` rather than `BTreeMap` because `flutter_rust_bridge` can
  /// translate `HashMap<K, V>` → Dart `Map<K, V>` but not `BTreeMap`.
  final Map<String, String> extra;

  const Document({
    required this.id,
    this.parentId,
    required this.kind,
    required this.title,
    required this.mimeType,
    required this.sizeBytes,
    required this.checksumSha256,
    required this.tags,
    required this.createdAtMs,
    required this.updatedAtMs,
    required this.extra,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parentId.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      checksumSha256.hashCode ^
      tags.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Document &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parentId == other.parentId &&
          kind == other.kind &&
          title == other.title &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          checksumSha256 == other.checksumSha256 &&
          tags == other.tags &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          extra == other.extra;
}

/// A persisted title/tag-set suggestion for a document.
///
/// rank 0 is the currently applied suggestion; rank >= 1 are pending
/// alternatives the user may review in the document info card. Choosing one
/// alternative marks every other pending suggestion of the same kind dismissed.
class DocumentSuggestion {
  final String id;
  final String documentId;
  final SuggestionKind kind;

  /// The suggested title text (kind = Title) or a JSON array of tag names
  /// (kind = Tags).
  final String payload;

  /// 0 = currently applied; higher = lower priority alternative.
  final int rank;
  final SuggestionSource source;
  final double confidence;
  final SuggestionStatus status;
  final PlatformInt64 createdAtMs;

  const DocumentSuggestion({
    required this.id,
    required this.documentId,
    required this.kind,
    required this.payload,
    required this.rank,
    required this.source,
    required this.confidence,
    required this.status,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      documentId.hashCode ^
      kind.hashCode ^
      payload.hashCode ^
      rank.hashCode ^
      source.hashCode ^
      confidence.hashCode ^
      status.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentSuggestion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          documentId == other.documentId &&
          kind == other.kind &&
          payload == other.payload &&
          rank == other.rank &&
          source == other.source &&
          confidence == other.confidence &&
          status == other.status &&
          createdAtMs == other.createdAtMs;
}

/// Aggregated accept/reject evidence for one term (the feedback model input).
class FeedbackStats {
  final double accepts;
  final double rejects;

  const FeedbackStats({required this.accepts, required this.rejects});

  @override
  int get hashCode => accepts.hashCode ^ rejects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedbackStats &&
          runtimeType == other.runtimeType &&
          accepts == other.accepts &&
          rejects == other.rejects;
}

/// A directed parent/child edge used to assemble the folder hierarchy.
class HierarchyLink {
  final String parentId;
  final String childId;

  /// Ordinal position of the child among its siblings.
  final int position;

  const HierarchyLink({
    required this.parentId,
    required this.childId,
    required this.position,
  });

  @override
  int get hashCode => parentId.hashCode ^ childId.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HierarchyLink &&
          runtimeType == other.runtimeType &&
          parentId == other.parentId &&
          childId == other.childId &&
          position == other.position;
}

/// Whether a hierarchy node is a leaf document or a folder/collection.
enum NodeKind { document, folder }

/// A saved (pinned) filter view: a named set of tag filters applied in one
/// tap from the filter bar. Tags are persisted sorted; applying a view
/// replaces the active tag-filter set.
class SavedView {
  final String name;
  final List<String> tags;

  const SavedView({required this.name, required this.tags});

  @override
  int get hashCode => name.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          tags == other.tags;
}

/// A single preference-evidence event recorded when the user reviews a
/// suggestion (accepted/rejected term, how strongly it was weighted).
///
/// The feedback model aggregates these per (kind, context, term) and re-ranks
/// future suggestions with an EWMA-decayed score. All data stays on-device.
class SuggestionFeedback {
  final String id;
  final SuggestionKind kind;
  final String context;
  final String term;
  final String action;
  final double weight;
  final PlatformInt64 createdAtMs;

  const SuggestionFeedback({
    required this.id,
    required this.kind,
    required this.context,
    required this.term,
    required this.action,
    required this.weight,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      context.hashCode ^
      term.hashCode ^
      action.hashCode ^
      weight.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuggestionFeedback &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          context == other.context &&
          term == other.term &&
          action == other.action &&
          weight == other.weight &&
          createdAtMs == other.createdAtMs;
}

/// What a suggestion proposes: a title, or a tag set.
enum SuggestionKind { title, tags }

/// How a suggestion was produced (surfaced in the UI for transparency).
enum SuggestionSource {
  /// The deterministic auto-organization pass run at ingestion time.
  ingest,

  /// A bulk "suggest titles/tags" pass.
  bulk,

  /// The per-document "Suggest" button (manual request).
  manualRequest,

  /// A user-typed contribution (own title/tag), recorded for learning.
  user,
}

/// Review state of a stored suggestion.
enum SuggestionStatus {
  /// Still shown in the document info card for the user to confirm/switch to.
  pending,

  /// The user confirmed this (or it was auto-applied as rank 0).
  applied,

  /// The user chose another alternative (or explicitly dismissed it).
  dismissed,
}

/// A user-defined tag. Tags may be nested (e.g. `receipts/2026`) via [`Tag::parent`].
class Tag {
  final String name;
  final String? parent;
  final String? color;

  const Tag({required this.name, this.parent, this.color});

  @override
  int get hashCode => name.hashCode ^ parent.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          parent == other.parent &&
          color == other.color;
}
