// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'ai.dart';
import 'api/ai.dart';
import 'api/assistant.dart';
import 'api/auto_org.dart';
import 'api/health.dart';
import 'api/ingest.dart';
import 'api/library.dart';
import 'api/p2p.dart';
import 'api/search.dart';
import 'api/storage.dart';
import 'api/sync.dart';
import 'auto_org/config.dart';
import 'auto_org/feedback.dart';
import 'auto_org/rules.dart';
import 'dart:async';
import 'dart:convert';
import 'domain.dart';
import 'frb_generated.dart';
import 'net/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'storage.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DocumentRepositoryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DocumentRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  DocumentRepository
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, FeedbackStats> dco_decode_Map_String_feedback_stats_None(
    dynamic raw,
  );

  @protected
  DocumentRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  RustStreamSink<AssistantStreamEventDto>
  dco_decode_StreamSink_assistant_stream_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<IngestEvent> dco_decode_StreamSink_ingest_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PeerEvent> dco_decode_StreamSink_peer_event_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncEventDto> dco_decode_StreamSink_sync_event_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveProviderInfo dco_decode_active_provider_info(dynamic raw);

  @protected
  AssistantEventKindDto dco_decode_assistant_event_kind_dto(dynamic raw);

  @protected
  AssistantReplyDto dco_decode_assistant_reply_dto(dynamic raw);

  @protected
  AssistantStreamEventDto dco_decode_assistant_stream_event_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ClassifyRequestDto dco_decode_box_autoadd_classify_request_dto(dynamic raw);

  @protected
  Content dco_decode_box_autoadd_content(dynamic raw);

  @protected
  Document dco_decode_box_autoadd_document(dynamic raw);

  @protected
  DocumentQuery dco_decode_box_autoadd_document_query(dynamic raw);

  @protected
  DocumentSuggestion dco_decode_box_autoadd_document_suggestion(dynamic raw);

  @protected
  EmbedRequestDto dco_decode_box_autoadd_embed_request_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  GenerateRequestDto dco_decode_box_autoadd_generate_request_dto(dynamic raw);

  @protected
  HierarchyLink dco_decode_box_autoadd_hierarchy_link(dynamic raw);

  @protected
  NodeKind dco_decode_box_autoadd_node_kind(dynamic raw);

  @protected
  OrgConfig dco_decode_box_autoadd_org_config(dynamic raw);

  @protected
  ProviderSettings dco_decode_box_autoadd_provider_settings(dynamic raw);

  @protected
  SearchRequestDto dco_decode_box_autoadd_search_request_dto(dynamic raw);

  @protected
  SuggestionFeedback dco_decode_box_autoadd_suggestion_feedback(dynamic raw);

  @protected
  SuggestionKind dco_decode_box_autoadd_suggestion_kind(dynamic raw);

  @protected
  SyncConflictDto dco_decode_box_autoadd_sync_conflict_dto(dynamic raw);

  @protected
  SyncNearDuplicateDto dco_decode_box_autoadd_sync_near_duplicate_dto(
    dynamic raw,
  );

  @protected
  SyncPhaseDto dco_decode_box_autoadd_sync_phase_dto(dynamic raw);

  @protected
  Tag dco_decode_box_autoadd_tag(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ClassifyRequestDto dco_decode_classify_request_dto(dynamic raw);

  @protected
  ClassifyResponseDto dco_decode_classify_response_dto(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  Content dco_decode_content(dynamic raw);

  @protected
  Document dco_decode_document(dynamic raw);

  @protected
  DocumentQuery dco_decode_document_query(dynamic raw);

  @protected
  DocumentRefDto dco_decode_document_ref_dto(dynamic raw);

  @protected
  DocumentSuggestion dco_decode_document_suggestion(dynamic raw);

  @protected
  DuplicatePairDto dco_decode_duplicate_pair_dto(dynamic raw);

  @protected
  EmbedRequestDto dco_decode_embed_request_dto(dynamic raw);

  @protected
  EmbedResponseDto dco_decode_embed_response_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeedbackStats dco_decode_feedback_stats(dynamic raw);

  @protected
  FilenameSource dco_decode_filename_source(dynamic raw);

  @protected
  GenerateMode dco_decode_generate_mode(dynamic raw);

  @protected
  GenerateRequestDto dco_decode_generate_request_dto(dynamic raw);

  @protected
  GenerateResponseDto dco_decode_generate_response_dto(dynamic raw);

  @protected
  HealthStatus dco_decode_health_status(dynamic raw);

  @protected
  HierarchyLink dco_decode_hierarchy_link(dynamic raw);

  @protected
  HighlightSpan dco_decode_highlight_span(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IngestEvent dco_decode_ingest_event(dynamic raw);

  @protected
  LabelScore dco_decode_label_score(dynamic raw);

  @protected
  LearningMode dco_decode_learning_mode(dynamic raw);

  @protected
  LibrarySyncReportDto dco_decode_library_sync_report_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Document> dco_decode_list_document(dynamic raw);

  @protected
  List<DocumentRefDto> dco_decode_list_document_ref_dto(dynamic raw);

  @protected
  List<DocumentSuggestion> dco_decode_list_document_suggestion(dynamic raw);

  @protected
  List<DuplicatePairDto> dco_decode_list_duplicate_pair_dto(dynamic raw);

  @protected
  List<HighlightSpan> dco_decode_list_highlight_span(dynamic raw);

  @protected
  List<LabelScore> dco_decode_list_label_score(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  List<PeerInfo> dco_decode_list_peer_info(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderSettings> dco_decode_list_provider_settings(dynamic raw);

  @protected
  List<(String, FeedbackStats)> dco_decode_list_record_string_feedback_stats(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SavedView> dco_decode_list_saved_view(dynamic raw);

  @protected
  List<SearchHitDto> dco_decode_list_search_hit_dto(dynamic raw);

  @protected
  List<SyncConflictDto> dco_decode_list_sync_conflict_dto(dynamic raw);

  @protected
  List<SyncResolutionDto> dco_decode_list_sync_resolution_dto(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  NodeKind dco_decode_node_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Content? dco_decode_opt_box_autoadd_content(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  NodeKind? dco_decode_opt_box_autoadd_node_kind(dynamic raw);

  @protected
  SuggestionKind? dco_decode_opt_box_autoadd_suggestion_kind(dynamic raw);

  @protected
  SyncConflictDto? dco_decode_opt_box_autoadd_sync_conflict_dto(dynamic raw);

  @protected
  SyncNearDuplicateDto? dco_decode_opt_box_autoadd_sync_near_duplicate_dto(
    dynamic raw,
  );

  @protected
  SyncPhaseDto? dco_decode_opt_box_autoadd_sync_phase_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OrgBulkStats dco_decode_org_bulk_stats(dynamic raw);

  @protected
  OrgConfig dco_decode_org_config(dynamic raw);

  @protected
  OrgPlan dco_decode_org_plan(dynamic raw);

  @protected
  PeerEvent dco_decode_peer_event(dynamic raw);

  @protected
  PeerEventKind dco_decode_peer_event_kind(dynamic raw);

  @protected
  PeerInfo dco_decode_peer_info(dynamic raw);

  @protected
  ProviderKind dco_decode_provider_kind(dynamic raw);

  @protected
  ProviderSettings dco_decode_provider_settings(dynamic raw);

  @protected
  (String, FeedbackStats) dco_decode_record_string_feedback_stats(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RuleSet dco_decode_rule_set(dynamic raw);

  @protected
  SavedView dco_decode_saved_view(dynamic raw);

  @protected
  SearchHitDto dco_decode_search_hit_dto(dynamic raw);

  @protected
  SearchMode dco_decode_search_mode(dynamic raw);

  @protected
  SearchRequestDto dco_decode_search_request_dto(dynamic raw);

  @protected
  SuggestOutcome dco_decode_suggest_outcome(dynamic raw);

  @protected
  SuggestionFeedback dco_decode_suggestion_feedback(dynamic raw);

  @protected
  SuggestionKind dco_decode_suggestion_kind(dynamic raw);

  @protected
  SuggestionSource dco_decode_suggestion_source(dynamic raw);

  @protected
  SuggestionStatus dco_decode_suggestion_status(dynamic raw);

  @protected
  SyncConflictDto dco_decode_sync_conflict_dto(dynamic raw);

  @protected
  SyncConflictKindDto dco_decode_sync_conflict_kind_dto(dynamic raw);

  @protected
  SyncEventDto dco_decode_sync_event_dto(dynamic raw);

  @protected
  SyncEventKindDto dco_decode_sync_event_kind_dto(dynamic raw);

  @protected
  SyncNearDuplicateDto dco_decode_sync_near_duplicate_dto(dynamic raw);

  @protected
  SyncPhaseDto dco_decode_sync_phase_dto(dynamic raw);

  @protected
  SyncResolutionDto dco_decode_sync_resolution_dto(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DocumentRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  DocumentRepository
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, FeedbackStats> sse_decode_Map_String_feedback_stats_None(
    SseDeserializer deserializer,
  );

  @protected
  DocumentRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AssistantStreamEventDto>
  sse_decode_StreamSink_assistant_stream_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<IngestEvent> sse_decode_StreamSink_ingest_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PeerEvent> sse_decode_StreamSink_peer_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEventDto> sse_decode_StreamSink_sync_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveProviderInfo sse_decode_active_provider_info(
    SseDeserializer deserializer,
  );

  @protected
  AssistantEventKindDto sse_decode_assistant_event_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  AssistantReplyDto sse_decode_assistant_reply_dto(
    SseDeserializer deserializer,
  );

  @protected
  AssistantStreamEventDto sse_decode_assistant_stream_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ClassifyRequestDto sse_decode_box_autoadd_classify_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  Content sse_decode_box_autoadd_content(SseDeserializer deserializer);

  @protected
  Document sse_decode_box_autoadd_document(SseDeserializer deserializer);

  @protected
  DocumentQuery sse_decode_box_autoadd_document_query(
    SseDeserializer deserializer,
  );

  @protected
  DocumentSuggestion sse_decode_box_autoadd_document_suggestion(
    SseDeserializer deserializer,
  );

  @protected
  EmbedRequestDto sse_decode_box_autoadd_embed_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  GenerateRequestDto sse_decode_box_autoadd_generate_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  HierarchyLink sse_decode_box_autoadd_hierarchy_link(
    SseDeserializer deserializer,
  );

  @protected
  NodeKind sse_decode_box_autoadd_node_kind(SseDeserializer deserializer);

  @protected
  OrgConfig sse_decode_box_autoadd_org_config(SseDeserializer deserializer);

  @protected
  ProviderSettings sse_decode_box_autoadd_provider_settings(
    SseDeserializer deserializer,
  );

  @protected
  SearchRequestDto sse_decode_box_autoadd_search_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  SuggestionFeedback sse_decode_box_autoadd_suggestion_feedback(
    SseDeserializer deserializer,
  );

  @protected
  SuggestionKind sse_decode_box_autoadd_suggestion_kind(
    SseDeserializer deserializer,
  );

  @protected
  SyncConflictDto sse_decode_box_autoadd_sync_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncNearDuplicateDto sse_decode_box_autoadd_sync_near_duplicate_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncPhaseDto sse_decode_box_autoadd_sync_phase_dto(
    SseDeserializer deserializer,
  );

  @protected
  Tag sse_decode_box_autoadd_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ClassifyRequestDto sse_decode_classify_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClassifyResponseDto sse_decode_classify_response_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  Content sse_decode_content(SseDeserializer deserializer);

  @protected
  Document sse_decode_document(SseDeserializer deserializer);

  @protected
  DocumentQuery sse_decode_document_query(SseDeserializer deserializer);

  @protected
  DocumentRefDto sse_decode_document_ref_dto(SseDeserializer deserializer);

  @protected
  DocumentSuggestion sse_decode_document_suggestion(
    SseDeserializer deserializer,
  );

  @protected
  DuplicatePairDto sse_decode_duplicate_pair_dto(SseDeserializer deserializer);

  @protected
  EmbedRequestDto sse_decode_embed_request_dto(SseDeserializer deserializer);

  @protected
  EmbedResponseDto sse_decode_embed_response_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeedbackStats sse_decode_feedback_stats(SseDeserializer deserializer);

  @protected
  FilenameSource sse_decode_filename_source(SseDeserializer deserializer);

  @protected
  GenerateMode sse_decode_generate_mode(SseDeserializer deserializer);

  @protected
  GenerateRequestDto sse_decode_generate_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  GenerateResponseDto sse_decode_generate_response_dto(
    SseDeserializer deserializer,
  );

  @protected
  HealthStatus sse_decode_health_status(SseDeserializer deserializer);

  @protected
  HierarchyLink sse_decode_hierarchy_link(SseDeserializer deserializer);

  @protected
  HighlightSpan sse_decode_highlight_span(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IngestEvent sse_decode_ingest_event(SseDeserializer deserializer);

  @protected
  LabelScore sse_decode_label_score(SseDeserializer deserializer);

  @protected
  LearningMode sse_decode_learning_mode(SseDeserializer deserializer);

  @protected
  LibrarySyncReportDto sse_decode_library_sync_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Document> sse_decode_list_document(SseDeserializer deserializer);

  @protected
  List<DocumentRefDto> sse_decode_list_document_ref_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentSuggestion> sse_decode_list_document_suggestion(
    SseDeserializer deserializer,
  );

  @protected
  List<DuplicatePairDto> sse_decode_list_duplicate_pair_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<HighlightSpan> sse_decode_list_highlight_span(
    SseDeserializer deserializer,
  );

  @protected
  List<LabelScore> sse_decode_list_label_score(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  List<PeerInfo> sse_decode_list_peer_info(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderSettings> sse_decode_list_provider_settings(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, FeedbackStats)> sse_decode_list_record_string_feedback_stats(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SavedView> sse_decode_list_saved_view(SseDeserializer deserializer);

  @protected
  List<SearchHitDto> sse_decode_list_search_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncConflictDto> sse_decode_list_sync_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncResolutionDto> sse_decode_list_sync_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  NodeKind sse_decode_node_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Content? sse_decode_opt_box_autoadd_content(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  NodeKind? sse_decode_opt_box_autoadd_node_kind(SseDeserializer deserializer);

  @protected
  SuggestionKind? sse_decode_opt_box_autoadd_suggestion_kind(
    SseDeserializer deserializer,
  );

  @protected
  SyncConflictDto? sse_decode_opt_box_autoadd_sync_conflict_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncNearDuplicateDto? sse_decode_opt_box_autoadd_sync_near_duplicate_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncPhaseDto? sse_decode_opt_box_autoadd_sync_phase_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OrgBulkStats sse_decode_org_bulk_stats(SseDeserializer deserializer);

  @protected
  OrgConfig sse_decode_org_config(SseDeserializer deserializer);

  @protected
  OrgPlan sse_decode_org_plan(SseDeserializer deserializer);

  @protected
  PeerEvent sse_decode_peer_event(SseDeserializer deserializer);

  @protected
  PeerEventKind sse_decode_peer_event_kind(SseDeserializer deserializer);

  @protected
  PeerInfo sse_decode_peer_info(SseDeserializer deserializer);

  @protected
  ProviderKind sse_decode_provider_kind(SseDeserializer deserializer);

  @protected
  ProviderSettings sse_decode_provider_settings(SseDeserializer deserializer);

  @protected
  (String, FeedbackStats) sse_decode_record_string_feedback_stats(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RuleSet sse_decode_rule_set(SseDeserializer deserializer);

  @protected
  SavedView sse_decode_saved_view(SseDeserializer deserializer);

  @protected
  SearchHitDto sse_decode_search_hit_dto(SseDeserializer deserializer);

  @protected
  SearchMode sse_decode_search_mode(SseDeserializer deserializer);

  @protected
  SearchRequestDto sse_decode_search_request_dto(SseDeserializer deserializer);

  @protected
  SuggestOutcome sse_decode_suggest_outcome(SseDeserializer deserializer);

  @protected
  SuggestionFeedback sse_decode_suggestion_feedback(
    SseDeserializer deserializer,
  );

  @protected
  SuggestionKind sse_decode_suggestion_kind(SseDeserializer deserializer);

  @protected
  SuggestionSource sse_decode_suggestion_source(SseDeserializer deserializer);

  @protected
  SuggestionStatus sse_decode_suggestion_status(SseDeserializer deserializer);

  @protected
  SyncConflictDto sse_decode_sync_conflict_dto(SseDeserializer deserializer);

  @protected
  SyncConflictKindDto sse_decode_sync_conflict_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncEventDto sse_decode_sync_event_dto(SseDeserializer deserializer);

  @protected
  SyncEventKindDto sse_decode_sync_event_kind_dto(SseDeserializer deserializer);

  @protected
  SyncNearDuplicateDto sse_decode_sync_near_duplicate_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncPhaseDto sse_decode_sync_phase_dto(SseDeserializer deserializer);

  @protected
  SyncResolutionDto sse_decode_sync_resolution_dto(
    SseDeserializer deserializer,
  );

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_feedback_stats_None(
    Map<String, FeedbackStats> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_assistant_stream_event_dto_Sse(
    RustStreamSink<AssistantStreamEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ingest_event_Sse(
    RustStreamSink<IngestEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_peer_event_Sse(
    RustStreamSink<PeerEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_dto_Sse(
    RustStreamSink<SyncEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_provider_info(
    ActiveProviderInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_assistant_event_kind_dto(
    AssistantEventKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_assistant_reply_dto(
    AssistantReplyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_assistant_stream_event_dto(
    AssistantStreamEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_classify_request_dto(
    ClassifyRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_document_query(
    DocumentQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_document_suggestion(
    DocumentSuggestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_embed_request_dto(
    EmbedRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_generate_request_dto(
    GenerateRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hierarchy_link(
    HierarchyLink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_kind(
    NodeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_org_config(
    OrgConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_provider_settings(
    ProviderSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_suggestion_feedback(
    SuggestionFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_suggestion_kind(
    SuggestionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_conflict_dto(
    SyncConflictDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_near_duplicate_dto(
    SyncNearDuplicateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_phase_dto(
    SyncPhaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_classify_request_dto(
    ClassifyRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_classify_response_dto(
    ClassifyResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_document_query(DocumentQuery self, SseSerializer serializer);

  @protected
  void sse_encode_document_ref_dto(
    DocumentRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_suggestion(
    DocumentSuggestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_duplicate_pair_dto(
    DuplicatePairDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embed_request_dto(
    EmbedRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embed_response_dto(
    EmbedResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_feedback_stats(FeedbackStats self, SseSerializer serializer);

  @protected
  void sse_encode_filename_source(
    FilenameSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_mode(GenerateMode self, SseSerializer serializer);

  @protected
  void sse_encode_generate_request_dto(
    GenerateRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_response_dto(
    GenerateResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_health_status(HealthStatus self, SseSerializer serializer);

  @protected
  void sse_encode_hierarchy_link(HierarchyLink self, SseSerializer serializer);

  @protected
  void sse_encode_highlight_span(HighlightSpan self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ingest_event(IngestEvent self, SseSerializer serializer);

  @protected
  void sse_encode_label_score(LabelScore self, SseSerializer serializer);

  @protected
  void sse_encode_learning_mode(LearningMode self, SseSerializer serializer);

  @protected
  void sse_encode_library_sync_report_dto(
    LibrarySyncReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document(List<Document> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_ref_dto(
    List<DocumentRefDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_suggestion(
    List<DocumentSuggestion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_duplicate_pair_dto(
    List<DuplicatePairDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_highlight_span(
    List<HighlightSpan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_label_score(
    List<LabelScore> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_info(List<PeerInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_settings(
    List<ProviderSettings> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_feedback_stats(
    List<(String, FeedbackStats)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_view(
    List<SavedView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit_dto(
    List<SearchHitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_conflict_dto(
    List<SyncConflictDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_resolution_dto(
    List<SyncResolutionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_node_kind(NodeKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content(
    Content? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_node_kind(
    NodeKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_suggestion_kind(
    SuggestionKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_conflict_dto(
    SyncConflictDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_near_duplicate_dto(
    SyncNearDuplicateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_phase_dto(
    SyncPhaseDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_org_bulk_stats(OrgBulkStats self, SseSerializer serializer);

  @protected
  void sse_encode_org_config(OrgConfig self, SseSerializer serializer);

  @protected
  void sse_encode_org_plan(OrgPlan self, SseSerializer serializer);

  @protected
  void sse_encode_peer_event(PeerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_peer_event_kind(PeerEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_peer_info(PeerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_provider_kind(ProviderKind self, SseSerializer serializer);

  @protected
  void sse_encode_provider_settings(
    ProviderSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_feedback_stats(
    (String, FeedbackStats) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_set(RuleSet self, SseSerializer serializer);

  @protected
  void sse_encode_saved_view(SavedView self, SseSerializer serializer);

  @protected
  void sse_encode_search_hit_dto(SearchHitDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_mode(SearchMode self, SseSerializer serializer);

  @protected
  void sse_encode_search_request_dto(
    SearchRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_suggest_outcome(
    SuggestOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_suggestion_feedback(
    SuggestionFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_suggestion_kind(
    SuggestionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_suggestion_source(
    SuggestionSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_suggestion_status(
    SuggestionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_conflict_dto(
    SyncConflictDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_conflict_kind_dto(
    SyncConflictKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_event_dto(SyncEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event_kind_dto(
    SyncEventKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_near_duplicate_dto(
    SyncNearDuplicateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_phase_dto(SyncPhaseDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_resolution_dto(
    SyncResolutionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    int ptr,
  );
}
