// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/health.dart';
import 'api/p2p.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain.dart';
import 'frb_generated.dart';
import 'net/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'storage.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DocumentRepositoryPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepositoryPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DocumentRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  DocumentRepository
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  DocumentRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    dynamic raw,
  );

  @protected
  RustStreamSink<PeerEvent> dco_decode_StreamSink_peer_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Content dco_decode_box_autoadd_content(dynamic raw);

  @protected
  Document dco_decode_box_autoadd_document(dynamic raw);

  @protected
  DocumentQuery dco_decode_box_autoadd_document_query(dynamic raw);

  @protected
  HierarchyLink dco_decode_box_autoadd_hierarchy_link(dynamic raw);

  @protected
  NodeKind dco_decode_box_autoadd_node_kind(dynamic raw);

  @protected
  PathAssignment dco_decode_box_autoadd_path_assignment(dynamic raw);

  @protected
  Tag dco_decode_box_autoadd_tag(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  Content dco_decode_content(dynamic raw);

  @protected
  Document dco_decode_document(dynamic raw);

  @protected
  DocumentQuery dco_decode_document_query(dynamic raw);

  @protected
  HealthStatus dco_decode_health_status(dynamic raw);

  @protected
  HierarchyLink dco_decode_hierarchy_link(dynamic raw);

  @protected
  HierarchyPath dco_decode_hierarchy_path(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Document> dco_decode_list_document(dynamic raw);

  @protected
  List<HierarchyPath> dco_decode_list_hierarchy_path(dynamic raw);

  @protected
  List<PeerInfo> dco_decode_list_peer_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  NodeKind dco_decode_node_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Content? dco_decode_opt_box_autoadd_content(dynamic raw);

  @protected
  NodeKind? dco_decode_opt_box_autoadd_node_kind(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PathAssignment dco_decode_path_assignment(dynamic raw);

  @protected
  PeerEvent dco_decode_peer_event(dynamic raw);

  @protected
  PeerEventKind dco_decode_peer_event_kind(dynamic raw);

  @protected
  PeerInfo dco_decode_peer_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DocumentRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  DocumentRepository
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  DocumentRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PeerEvent> sse_decode_StreamSink_peer_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Content sse_decode_box_autoadd_content(SseDeserializer deserializer);

  @protected
  Document sse_decode_box_autoadd_document(SseDeserializer deserializer);

  @protected
  DocumentQuery sse_decode_box_autoadd_document_query(
    SseDeserializer deserializer,
  );

  @protected
  HierarchyLink sse_decode_box_autoadd_hierarchy_link(
    SseDeserializer deserializer,
  );

  @protected
  NodeKind sse_decode_box_autoadd_node_kind(SseDeserializer deserializer);

  @protected
  PathAssignment sse_decode_box_autoadd_path_assignment(
    SseDeserializer deserializer,
  );

  @protected
  Tag sse_decode_box_autoadd_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  Content sse_decode_content(SseDeserializer deserializer);

  @protected
  Document sse_decode_document(SseDeserializer deserializer);

  @protected
  DocumentQuery sse_decode_document_query(SseDeserializer deserializer);

  @protected
  HealthStatus sse_decode_health_status(SseDeserializer deserializer);

  @protected
  HierarchyLink sse_decode_hierarchy_link(SseDeserializer deserializer);

  @protected
  HierarchyPath sse_decode_hierarchy_path(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Document> sse_decode_list_document(SseDeserializer deserializer);

  @protected
  List<HierarchyPath> sse_decode_list_hierarchy_path(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerInfo> sse_decode_list_peer_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  NodeKind sse_decode_node_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Content? sse_decode_opt_box_autoadd_content(SseDeserializer deserializer);

  @protected
  NodeKind? sse_decode_opt_box_autoadd_node_kind(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PathAssignment sse_decode_path_assignment(SseDeserializer deserializer);

  @protected
  PeerEvent sse_decode_peer_event(SseDeserializer deserializer);

  @protected
  PeerEventKind sse_decode_peer_event_kind(SseDeserializer deserializer);

  @protected
  PeerInfo sse_decode_peer_info(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    DocumentRepository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_peer_event_Sse(
    RustStreamSink<PeerEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_document_query(
    DocumentQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hierarchy_link(
    HierarchyLink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_kind(
    NodeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_path_assignment(
    PathAssignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_document_query(DocumentQuery self, SseSerializer serializer);

  @protected
  void sse_encode_health_status(HealthStatus self, SseSerializer serializer);

  @protected
  void sse_encode_hierarchy_link(HierarchyLink self, SseSerializer serializer);

  @protected
  void sse_encode_hierarchy_path(HierarchyPath self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document(List<Document> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hierarchy_path(
    List<HierarchyPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_info(List<PeerInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_node_kind(NodeKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content(
    Content? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_node_kind(
    NodeKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_path_assignment(
    PathAssignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_event(PeerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_peer_event_kind(PeerEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_peer_info(PeerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepositoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_docer_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepositoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepositoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_docer_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepository =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDocumentRepositoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
