// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ingest.freezed.dart';

@freezed
sealed class ProgressEvent with _$ProgressEvent {
  const ProgressEvent._();

  /// About to copy the file bytes into the blob store.
  const factory ProgressEvent.processing({required String fileName}) =
      ProgressEvent_Processing;

  /// Text extraction in progress (PDF pages, OCR chunks, etc.).
  const factory ProgressEvent.extracting({
    required String fileName,

    /// 0..=100 across the extraction phase.
    required int percent,
  }) = ProgressEvent_Extracting;

  /// The file was fully ingested (metadata + blob + content stored).
  const factory ProgressEvent.completed({
    required String fileName,
    required String documentId,
  }) = ProgressEvent_Completed;

  /// The file could not be ingested.
  const factory ProgressEvent.failed({
    required String fileName,
    required String error,
  }) = ProgressEvent_Failed;
}
