// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A predicate for listing documents.
class DocumentQuery {
  final String? parent;
  final List<String> tags;
  final NodeKind? kind;
  final int? limit;
  final int? offset;

  const DocumentQuery({
    this.parent,
    required this.tags,
    this.kind,
    this.limit,
    this.offset,
  });

  @override
  int get hashCode =>
      parent.hashCode ^
      tags.hashCode ^
      kind.hashCode ^
      limit.hashCode ^
      offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentQuery &&
          runtimeType == other.runtimeType &&
          parent == other.parent &&
          tags == other.tags &&
          kind == other.kind &&
          limit == other.limit &&
          offset == other.offset;
}
