// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ai.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_settings`, `manager`, `to_settings`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// List configured providers (with `has_api_key` computed without exposing keys).
List<ProviderSettings> aiListProviders() =>
    RustLib.instance.api.crateApiAiAiListProviders();

/// Snapshot of the currently active provider + model.
ActiveProviderInfo aiActiveProvider() =>
    RustLib.instance.api.crateApiAiAiActiveProvider();

/// Select the active provider and (optionally) model at runtime.
ActiveProviderInfo aiSelectProvider({required String kind, String? model}) =>
    RustLib.instance.api.crateApiAiAiSelectProvider(kind: kind, model: model);

/// Save (upsert) a provider's configuration. Secrets are *not* included.
void aiSaveProviderSettings({required ProviderSettings settings}) =>
    RustLib.instance.api.crateApiAiAiSaveProviderSettings(settings: settings);

/// Store an API key in the OS keychain for the given provider kind.
void aiSetApiKey({required String kind, required String key}) =>
    RustLib.instance.api.crateApiAiAiSetApiKey(kind: kind, key: key);

/// Remove a stored API key for the given provider kind.
void aiRemoveApiKey({required String kind}) =>
    RustLib.instance.api.crateApiAiAiRemoveApiKey(kind: kind);

/// Generate text using the active provider.
Future<GenerateResponseDto> aiGenerate({required GenerateRequestDto req}) =>
    RustLib.instance.api.crateApiAiAiGenerate(req: req);

/// Classify text into one of `labels` using the active provider.
Future<ClassifyResponseDto> aiClassify({required ClassifyRequestDto req}) =>
    RustLib.instance.api.crateApiAiAiClassify(req: req);

/// Embed text using the active provider.
Future<EmbedResponseDto> aiEmbed({required EmbedRequestDto req}) =>
    RustLib.instance.api.crateApiAiAiEmbed(req: req);

/// Snapshot of the active provider + model (Dart DTO).
class ActiveProviderInfo {
  final String kind;
  final String model;
  final String? baseUrl;
  final bool hasApiKey;

  const ActiveProviderInfo({
    required this.kind,
    required this.model,
    this.baseUrl,
    required this.hasApiKey,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ model.hashCode ^ baseUrl.hashCode ^ hasApiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveProviderInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          model == other.model &&
          baseUrl == other.baseUrl &&
          hasApiKey == other.hasApiKey;
}

/// A classification request (Dart DTO).
class ClassifyRequestDto {
  final String text;
  final List<String> labels;

  const ClassifyRequestDto({required this.text, required this.labels});

  @override
  int get hashCode => text.hashCode ^ labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassifyRequestDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          labels == other.labels;
}

/// A classification response (Dart DTO).
class ClassifyResponseDto {
  final String label;
  final List<LabelScore> scores;

  const ClassifyResponseDto({required this.label, required this.scores});

  @override
  int get hashCode => label.hashCode ^ scores.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassifyResponseDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          scores == other.scores;
}

/// An embedding request (Dart DTO).
class EmbedRequestDto {
  final String text;

  const EmbedRequestDto({required this.text});

  @override
  int get hashCode => text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedRequestDto &&
          runtimeType == other.runtimeType &&
          text == other.text;
}

/// An embedding response (Dart DTO).
class EmbedResponseDto {
  final Float32List vector;
  final int dimensions;

  const EmbedResponseDto({required this.vector, required this.dimensions});

  @override
  int get hashCode => vector.hashCode ^ dimensions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedResponseDto &&
          runtimeType == other.runtimeType &&
          vector == other.vector &&
          dimensions == other.dimensions;
}

/// A text-generation request (Dart DTO).
class GenerateRequestDto {
  final String prompt;
  final String? system;
  final GenerateMode mode;
  final int? maxTokens;
  final double? temperature;

  const GenerateRequestDto({
    required this.prompt,
    this.system,
    required this.mode,
    this.maxTokens,
    this.temperature,
  });

  @override
  int get hashCode =>
      prompt.hashCode ^
      system.hashCode ^
      mode.hashCode ^
      maxTokens.hashCode ^
      temperature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateRequestDto &&
          runtimeType == other.runtimeType &&
          prompt == other.prompt &&
          system == other.system &&
          mode == other.mode &&
          maxTokens == other.maxTokens &&
          temperature == other.temperature;
}

/// A text-generation response (Dart DTO).
class GenerateResponseDto {
  final String content;
  final int promptTokens;
  final int completionTokens;

  const GenerateResponseDto({
    required this.content,
    required this.promptTokens,
    required this.completionTokens,
  });

  @override
  int get hashCode =>
      content.hashCode ^ promptTokens.hashCode ^ completionTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateResponseDto &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens;
}

/// A single label score (Dart DTO).
class LabelScore {
  final String label;
  final double score;

  const LabelScore({required this.label, required this.score});

  @override
  int get hashCode => label.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LabelScore &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          score == other.score;
}

/// One selectable model on a provider (Dart DTO).
class ModelInfo {
  final String name;
  final String displayName;

  const ModelInfo({required this.name, required this.displayName});

  @override
  int get hashCode => name.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName;
}

/// Re-exported provider-kind enum so Dart sees a single shared type.
enum ProviderKind {
  builtin,
  ollama,

  /// An OpenAI-compatible endpoint. Named `Openai` (single word) so the
  /// generated Dart enum member is `openai`, matching the stored `kind` id.
  openai,
}

/// Configuration for a single provider backend (Dart DTO; no secrets).
class ProviderSettings {
  final ProviderKind kind;
  final String? baseUrl;
  final String model;
  final bool enabled;
  final List<ModelInfo> models;

  /// Whether an API key is currently stored for this backend.
  final bool hasApiKey;

  const ProviderSettings({
    required this.kind,
    this.baseUrl,
    required this.model,
    required this.enabled,
    required this.models,
    required this.hasApiKey,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      enabled.hashCode ^
      models.hashCode ^
      hasApiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderSettings &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          enabled == other.enabled &&
          models == other.models &&
          hasApiKey == other.hasApiKey;
}
