// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_provider`, `assistant`, `search_index`, `to_ref_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Index (or re-index) a document's extracted text into the assistant's
/// retrieval store. Call after content extraction so the chunk is searchable.
void assistantIndexDocument({
  required String documentId,
  required String text,
}) => RustLib.instance.api.crateApiAssistantAssistantIndexDocument(
  documentId: documentId,
  text: text,
);

/// Remove a document from the assistant's retrieval store.
void assistantRemoveDocument({required String documentId}) => RustLib
    .instance
    .api
    .crateApiAssistantAssistantRemoveDocument(documentId: documentId);

/// Clear the assistant's conversational history.
void assistantClearHistory() =>
    RustLib.instance.api.crateApiAssistantAssistantClearHistory();

/// Answer a question with citations, using the active AI provider.
///
/// Falls back to retrieved excerpts (with source references) when no provider is
/// available.
Future<AssistantReplyDto> assistantAsk({required String question}) =>
    RustLib.instance.api.crateApiAssistantAssistantAsk(question: question);

/// Ask a question, streaming answer tokens to Dart over `sink`, then a final
/// [`AssistantEventKindDto::Done`] event carrying the citations.
///
/// The stream stays open until generation completes (or the Dart side closes it).
Stream<AssistantStreamEventDto> assistantAskStream({
  required String question,
}) => RustLib.instance.api.crateApiAssistantAssistantAskStream(
  question: question,
);

/// The kind of an [`AssistantStreamEventDto`].
enum AssistantEventKindDto { token, done }

/// A complete assistant response.
class AssistantReplyDto {
  final String answer;
  final List<DocumentRefDto> references;

  const AssistantReplyDto({required this.answer, required this.references});

  @override
  int get hashCode => answer.hashCode ^ references.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssistantReplyDto &&
          runtimeType == other.runtimeType &&
          answer == other.answer &&
          references == other.references;
}

/// An incremental answer chunk (or the final citations), delivered over the
/// [`assistant_ask_stream`] Dart `Stream`.
class AssistantStreamEventDto {
  final AssistantEventKindDto kind;

  /// Populated for [`AssistantEventKindDto::Token`].
  final String? token;

  /// Populated for [`AssistantEventKindDto::Done`].
  final List<DocumentRefDto> references;

  const AssistantStreamEventDto({
    required this.kind,
    this.token,
    required this.references,
  });

  @override
  int get hashCode => kind.hashCode ^ token.hashCode ^ references.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssistantStreamEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          token == other.token &&
          references == other.references;
}

/// A citation pointing at a document that supports part of an answer.
class DocumentRefDto {
  final String documentId;
  final String excerpt;

  const DocumentRefDto({required this.documentId, required this.excerpt});

  @override
  int get hashCode => documentId.hashCode ^ excerpt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentRefDto &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          excerpt == other.excerpt;
}
