// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../auto_org/config.dart';
import '../auto_org/feedback.dart';
import '../auto_org/rules.dart';
import '../domain.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';

// These functions are ignored because they are not marked as `pub`: `any`, `apply_plan`, `auto_org_reorganize_one_impl`, `build_corpus`, `flag_is_set`, `new_uuid`, `organize_document`, `payload_terms`, `preference_model`, `record_accept`, `record_reject`, `store_plan_suggestions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApplyCounts`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Run the deterministic (non-generative) organizer on `document_id`, returning
/// the [`OrgPlan`] of suggested tags, placement, rename, and dedup.
///
/// Declared `async` so FRB executes it on Rust's async worker pool instead of
/// the Dart UI isolate. This is the primitive behind the per-file "Suggest
/// title/tags" buttons, and the deterministic pass can be heavy (mmap the raw
/// bytes, minhash, per-document FTS + KNN scans) — running it synchronously on
/// the caller's thread would freeze the interface, exactly like the bulk
/// `auto_org_reorganize_all` path discussed in [`auto_org_reorganize_selected`].
///
/// The repository is taken by *reference* (FRB `Auto_Ref` encoding), so the
/// shared `Arc<Mutex<_>>` handle is borrowed rather than owned/disposed. Callers
/// may reuse the same repository handle for later bridge calls (e.g. the ingest
/// pipeline or a subsequent reorganize) without hitting a disposed opaque.
Future<OrgPlan> autoOrgOrganize({
  required DocumentRepository repo,
  required String documentId,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgOrganize(
  repo: repo,
  documentId: documentId,
  config: config,
);

/// Re-run the deterministic auto-organization pass across **all** documents,
/// preserving every user's manual edits.
///
/// Iterates [`DocumentStore::query`], runs the same [`DeterministicOrganizer`]
/// as ingestion, and applies the suggestion through the *normal* update paths:
///
/// * title applied only when `extra['title_manual']` is **not** truthy;
/// * tags applied only when `extra['tags_manual']` is **not** truthy;
/// * placement always applied (a hierarchy move is not part of the manual
///   title/tag contract).
///
/// Each applied change is written via [`DocumentRepository::update_title`] /
/// [`DocumentRepository::set_tags`] and the fresh tags/paths are mirrored into
/// the in-memory search index via [`crate::api::search::search_set_metadata`]
/// (that mirror also happens inside the two update paths). The pass needs **no
/// AI provider** — it is the same deterministic pipeline used at ingestion.
OrgBulkStats autoOrgReorganizeAll({
  required DocumentRepository repo,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgReorganizeAll(
  repo: repo,
  config: config,
);

/// Re-run the deterministic auto-organization pass on the **selected**
/// documents only, preserving every user's manual edits.
///
/// This is the signalled "Re-organize selected" bulk action. The classic
/// `auto_org_reorganize_all` is a `#[frb(sync)]` bridge call that executes the
/// whole corpus on the **Dart UI isolate** (the SSE sync path performs the FFI
/// synchronously on the caller's thread), freezing the interface for the whole
/// pass. Marking this function `async` makes FRB run it on Rust's async worker
/// pool, so the UI stays responsive while the pass runs.
///
/// Semantics are identical to [`auto_org_reorganize_one_impl`] — title applied
/// only when `extra['title_manual']` is not truthy, tags only when
/// `extra['tags_manual']` is not truthy, placement always applied — but the
/// corpus snapshot and organizer are built **once** for the whole batch instead
/// of once per document.
Future<OrgBulkStats> autoOrgReorganizeSelected({
  required DocumentRepository repo,
  required List<String> ids,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgReorganizeSelected(
  repo: repo,
  ids: ids,
  config: config,
);

/// Re-run the deterministic auto-organization pass on one document, honoring
/// the `title_manual` / `tags_manual` flags (a user's hand-edited title or tags
/// are never overwritten). Returns the resulting applied [`OrgPlan`].
///
/// Bridges the per-file "Suggest title & tags" button in the document detail
/// view: instead of applying suggestions naively on the Dart side, the button
/// can call this and let the core apply only the parts the user has not
/// manually set, then refresh the search metadata.
OrgPlan autoOrgReorganizeOne({
  required DocumentRepository repo,
  required String documentId,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgReorganizeOne(
  repo: repo,
  documentId: documentId,
  config: config,
);

/// Regenerate just the filename via the generative LLM tier, returning the new
/// suggested title. Fails if no generative provider is configured; the caller
/// should fall back to the deterministic template title.
Future<String> autoOrgGenerateFilename({
  required DocumentRepository repo,
  required String documentId,
  required String model,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgGenerateFilename(
  repo: repo,
  documentId: documentId,
  model: model,
);

/// A convenience default [`OrgConfig`] for Dart, populated with the default rule
/// set and templates.
OrgConfig autoOrgDefaultConfig() =>
    RustLib.instance.api.crateApiAutoOrgAutoOrgDefaultConfig();

/// List a document's suggestions (pending + applied), ranked per kind.
Future<List<DocumentSuggestion>> autoOrgListSuggestions({
  required DocumentRepository repo,
  required String documentId,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgListSuggestions(
  repo: repo,
  documentId: documentId,
);

/// Apply one pending alternative suggestion to the document: apply its payload
/// through the normal update paths, record feedback (accepted terms of the
/// chosen alternative + rejected terms of the previously-applied rank 0 that
/// are not in the chosen set), and dismiss every other pending suggestion of
/// the same kind (the "alternatives disappear after choice" contract).
Future<void> autoOrgApplySuggestion({
  required DocumentRepository repo,
  required String documentId,
  required String suggestionId,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgApplySuggestion(
  repo: repo,
  documentId: documentId,
  suggestionId: suggestionId,
);

/// Keep the currently applied value (rank 0) for a suggestion kind: record
/// accepted feedback for the applied terms + rejected for pending alternatives'
/// distinctive terms, and dismiss all pending of that kind.
Future<void> autoOrgConfirmCurrent({
  required DocumentRepository repo,
  required String documentId,
  required SuggestionKind kind,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgConfirmCurrent(
  repo: repo,
  documentId: documentId,
  kind: kind,
);

/// Dismiss one pending suggestion (with reject feedback for its terms).
Future<void> autoOrgDismissSuggestion({
  required DocumentRepository repo,
  required String documentId,
  required String suggestionId,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgDismissSuggestion(
  repo: repo,
  documentId: documentId,
  suggestionId: suggestionId,
);

/// Suggest a title for a document: apply the top suggestion (if any), persist
/// the full candidate list (including the pre-suggestion old title) as pending
/// for review, and return the outcome.
///
/// The top suggestion is applied **without** stamping `title_manual` (it is a
/// suggestion, not a user rename). The pre-suggestion value is always among the
/// alternatives so the user can switch back to it.
Future<SuggestOutcome> autoOrgSuggestTitle({
  required DocumentRepository repo,
  required String documentId,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgSuggestTitle(
  repo: repo,
  documentId: documentId,
  config: config,
);

/// Suggest tags for a document: apply the top tag set (if any), persist the
/// full candidate list (including the pre-suggestion old tags) as pending for
/// review, and return the outcome.
///
/// The top suggestion is applied **without** stamping `tags_manual`. The
/// pre-suggestion value is always among the alternatives so the user can switch
/// back to it.
Future<SuggestOutcome> autoOrgSuggestTags({
  required DocumentRepository repo,
  required String documentId,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgSuggestTags(
  repo: repo,
  documentId: documentId,
  config: config,
);

/// Wipe all learned feedback (settings "reset learning").
Future<void> autoOrgResetLearning({required DocumentRepository repo}) =>
    RustLib.instance.api.crateApiAutoOrgAutoOrgResetLearning(repo: repo);

/// Complete the suggestion review ("poll") for one kind after the user
/// manually edited that kind's value: dismiss every suggestion row of the
/// kind (pending alternatives AND the stale applied rank-0, whose value no
/// longer matches the document), and — when `record_feedback` is true —
/// record rejected feedback for every generated term the user did NOT keep.
/// The kept values are read from the document's current state (the manual
/// edit has already been persisted by the caller). Returns the number of
/// rows marked dismissed.
///
/// Why the applied rank-0 row is dismissed: unlike [`auto_org_confirm_current`]
/// (which keeps the applied value), a manual edit means the user changed the
/// document to a value *not* in the suggestion list. The old rank-0 row is
/// therefore stale — it no longer represents the document's current state and
/// must be removed from the UI along with all pending alternatives.
Future<int> autoOrgResolveManualEdit({
  required DocumentRepository repo,
  required String documentId,
  required SuggestionKind kind,
  required bool recordFeedback,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgResolveManualEdit(
  repo: repo,
  documentId: documentId,
  kind: kind,
  recordFeedback: recordFeedback,
);

/// A convenience default [`RuleSet`] (empty placement rules + `/inbox` fallback).
RuleSet autoOrgDefaultRules() =>
    RustLib.instance.api.crateApiAutoOrgAutoOrgDefaultRules();

/// The aggregate outcome of a bulk re-organization pass over the whole library.
class OrgBulkStats {
  /// Documents examined by the pass.
  final BigInt total;

  /// Documents whose tags/title/placement changed as a result.
  final BigInt updated;

  /// Documents left untouched (already matching, or manual-edit flags set).
  final BigInt skipped;

  const OrgBulkStats({
    required this.total,
    required this.updated,
    required this.skipped,
  });

  @override
  int get hashCode => total.hashCode ^ updated.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrgBulkStats &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          updated == other.updated &&
          skipped == other.skipped;
}

/// The outcome of a per-document "Suggest title"/"Suggest tags" run.
class SuggestOutcome {
  /// Applied (value changed) | AlreadyCurrent (no change needed) |
  /// NoSuggestion (pipeline produced nothing).
  final String status;

  /// How many pending alternatives were stored for the review card (0 when
  /// nothing to review).
  final BigInt storedPending;

  const SuggestOutcome({required this.status, required this.storedPending});

  @override
  int get hashCode => status.hashCode ^ storedPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuggestOutcome &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          storedPending == other.storedPending;
}
