// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../auto_org/config.dart';
import '../auto_org/rules.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';

// These functions are ignored because they are not marked as `pub`: `build_corpus`

/// Run the deterministic (non-generative) organizer on `document_id`, returning
/// the [`OrgPlan`] of suggested tags, placement, rename, and dedup.
OrgPlan autoOrgOrganize({
  required DocumentRepository repo,
  required String documentId,
  required OrgConfig config,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgOrganize(
  repo: repo,
  documentId: documentId,
  config: config,
);

/// Regenerate just the filename via the generative LLM tier, returning the new
/// suggested title. Fails if no generative provider is configured; the caller
/// should fall back to the deterministic template title.
Future<String> autoOrgGenerateFilename({
  required DocumentRepository repo,
  required String documentId,
  required String model,
}) => RustLib.instance.api.crateApiAutoOrgAutoOrgGenerateFilename(
  repo: repo,
  documentId: documentId,
  model: model,
);

/// A convenience default [`OrgConfig`] for Dart, populated with the default rule
/// set and templates.
OrgConfig autoOrgDefaultConfig() =>
    RustLib.instance.api.crateApiAutoOrgAutoOrgDefaultConfig();

/// A convenience default [`RuleSet`] (empty placement rules + `/inbox` fallback).
RuleSet autoOrgDefaultRules() =>
    RustLib.instance.api.crateApiAutoOrgAutoOrgDefaultRules();
