// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_millis`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Liveness/readiness probe. Called from Dart at startup.
///
/// `sync` marks this as a synchronous bridge function (no `await` in Dart).
HealthStatus healthCheck() => RustLib.instance.api.crateApiHealthHealthCheck();

/// Status returned by [`health_check`] and shown in the app's status bar.
class HealthStatus {
  /// Always `true` when the engine is reachable and initialized.
  final bool ok;

  /// Engine crate name.
  final String engine;

  /// Crate version (from `Cargo.toml`).
  final String engineVersion;

  /// Host OS as reported by Rust (`std::env::consts::OS`).
  final String platform;

  /// Wall-clock time of the check, milliseconds since the Unix epoch.
  final PlatformInt64 timestampMs;

  const HealthStatus({
    required this.ok,
    required this.engine,
    required this.engineVersion,
    required this.platform,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      engine.hashCode ^
      engineVersion.hashCode ^
      platform.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthStatus &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          engine == other.engine &&
          engineVersion == other.engineVersion &&
          platform == other.platform &&
          timestampMs == other.timestampMs;
}
