// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';

// These functions are ignored because they are not marked as `pub`: `to_ingest_option`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiProgressSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `add`

/// Ingest a batch of files from disk into the repository.
///
/// FRB "stream mode" (like `crate::api::p2p::p2p_events`): the Dart call site
/// returns a `Stream<IngestEvent>` carrying one event per file
/// (`processing` → `extracting` → `completed`/`failed`). The document id for a
/// successful file is delivered inside the `completed` event's `document_id`
/// field, so no second return channel is needed. The processing happens on the
/// FRB worker thread (blocking) while events flow through the sink.
Stream<IngestEvent> ingestFiles({
  required DocumentRepository repo,
  required List<String> paths,
  String? destinationPath,
  String? titleOverride,
  required bool skipExisting,
}) => RustLib.instance.api.crateApiIngestIngestFiles(
  repo: repo,
  paths: paths,
  destinationPath: destinationPath,
  titleOverride: titleOverride,
  skipExisting: skipExisting,
);

/// A single progress event pushed over the Dart stream while files are
/// ingested. Kept as a plain struct/string DTO (not a data-carrying enum) so
/// the generated Dart binding is a simple class.
class IngestEvent {
  /// Event kind: `"processing"`, `"extracting"`, `"completed"`, or `"failed"`.
  final String kind;

  /// File name (basename) the event concerns.
  final String fileName;

  /// 0..=100 for extracting events; 0 otherwise.
  final int percent;

  /// Document id for completed events; empty otherwise.
  final String documentId;

  /// Error message for failed events; empty otherwise.
  final String error;

  const IngestEvent({
    required this.kind,
    required this.fileName,
    required this.percent,
    required this.documentId,
    required this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      fileName.hashCode ^
      percent.hashCode ^
      documentId.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngestEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          fileName == other.fileName &&
          percent == other.percent &&
          documentId == other.documentId &&
          error == other.error;
}
