// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// The configured library mirror directory, or `None` when not set.
String? libraryGetDirectory({required DocumentRepository repo}) =>
    RustLib.instance.api.crateApiLibraryLibraryGetDirectory(repo: repo);

/// Set (or clear, when `None`) the library mirror directory.
///
/// Persists `<root>/library_dir.txt` before swapping the handle (a crash never
/// leaves metadata pointing at an un-writable location).
void librarySetDirectory({required DocumentRepository repo, String? dir}) =>
    RustLib.instance.api.crateApiLibraryLibrarySetDirectory(
      repo: repo,
      dir: dir,
    );

/// Reconcile the repository with its configured library directory.
///
/// Errors when no library folder is configured.
LibrarySyncReportDto librarySync({required DocumentRepository repo}) =>
    RustLib.instance.api.crateApiLibraryLibrarySync(repo: repo);

/// The on-disk path of a document's mirrored library file, when it exists.
///
/// Used for reveal-in-finder / open-directly from the real file (no temp copy
/// needed). Returns `None` when the library is unset, the document has no
/// stamped `file_name`, or the file no longer exists on disk.
String? libraryFilePath({
  required DocumentRepository repo,
  required String id,
}) => RustLib.instance.api.crateApiLibraryLibraryFilePath(repo: repo, id: id);

/// The outcome of one reconciliation pass, as plain Dart-friendly data.
class LibrarySyncReportDto {
  /// Document ids ingested from newly-claimed directory files.
  final List<String> added;

  /// Document ids deleted because their file vanished from the directory.
  final List<String> removed;

  /// Document ids linked to an existing directory file (same bytes).
  final List<String> linked;

  /// Per-file failures: `(file_name, error)`. The pass always continues.
  final List<(String, String)> failed;

  const LibrarySyncReportDto({
    required this.added,
    required this.removed,
    required this.linked,
    required this.failed,
  });

  static Future<LibrarySyncReportDto> default_() =>
      RustLib.instance.api.crateApiLibraryLibrarySyncReportDtoDefault();

  @override
  int get hashCode =>
      added.hashCode ^ removed.hashCode ^ linked.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibrarySyncReportDto &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          removed == other.removed &&
          linked == other.linked &&
          failed == other.failed;
}
