// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../net/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`, `to_dto`, `to_event_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// The local device's stable peer id (base58 libp2p `PeerId`).
String p2PLocalPeerId() => RustLib.instance.api.crateApiP2PP2PLocalPeerId();

/// Snapshot of currently known peers and their connection state.
List<PeerInfo> p2PListPeers() => RustLib.instance.api.crateApiP2PP2PListPeers();

/// Dial a peer by id and multiaddr.
void p2PConnect({required String peerId, required String addr}) =>
    RustLib.instance.api.crateApiP2PP2PConnect(peerId: peerId, addr: addr);

/// Open a Dart `Stream` of peer events (discovery + connection state changes).
///
/// The returned stream stays open for the life of the subscription, receiving
/// one [`PeerEvent`] per connectivity change.
Stream<PeerEvent> p2PEvents() => RustLib.instance.api.crateApiP2PP2PEvents();

/// A connectivity change pushed to Dart over the [`p2p_events`] stream.
///
/// Modeled as a plain struct (not a data-carrying enum) so the generated Dart
/// binding is a simple class rather than a freezed sealed union.
class PeerEvent {
  final PeerEventKind kind;
  final String peerId;

  /// Listen addresses for the peer; populated only for [`PeerEventKind::Discovered`].
  final List<String> addresses;

  const PeerEvent({
    required this.kind,
    required this.peerId,
    required this.addresses,
  });

  @override
  int get hashCode => kind.hashCode ^ peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

/// The kind of connectivity change an event describes.
enum PeerEventKind { discovered, expired, connected, disconnected }

/// A discovered peer / device and its current connection state (Dart DTO).
class PeerInfo {
  final String id;
  final List<String> addresses;
  final ConnectionState state;

  const PeerInfo({
    required this.id,
    required this.addresses,
    required this.state,
  });

  @override
  int get hashCode => id.hashCode ^ addresses.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          addresses == other.addresses &&
          state == other.state;
}
