// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`

/// Index (or re-index) a document's extracted text across exact, semantic, and
/// near-duplicate backends. Call after content extraction.
void searchIndexDocument({required String documentId, required String text}) =>
    RustLib.instance.api.crateApiSearchSearchIndexDocument(
      documentId: documentId,
      text: text,
    );

/// Remove a document from all search backends.
void searchRemoveDocument({required String documentId}) => RustLib.instance.api
    .crateApiSearchSearchRemoveDocument(documentId: documentId);

/// Exact full-text search (FTS5 word / `"phrase"` / boolean queries).
List<SearchHitDto> searchExact({required String query, required int limit}) =>
    RustLib.instance.api.crateApiSearchSearchExact(query: query, limit: limit);

/// Semantic search via local embeddings, ranked by cosine similarity.
List<SearchHitDto> searchSemantic({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiSearchSearchSemantic(
  query: query,
  limit: limit,
);

/// Near-duplicate detection: list all candidate duplicate pairs.
List<DuplicatePairDto> searchDuplicates() =>
    RustLib.instance.api.crateApiSearchSearchDuplicates();

/// Near-duplicate detection: documents similar to `text` above `threshold`.
List<String> searchFindDuplicates({
  required String text,
  required double threshold,
}) => RustLib.instance.api.crateApiSearchSearchFindDuplicates(
  text: text,
  threshold: threshold,
);

/// Embed `text` into a dense vector using the shared local embedding model.
///
/// This exposes the single shared embedding store's `embed(text) -> Vec<f32>`
/// surface to Dart, so later tasks (e.g. auto-organization) reuse it rather than
/// building their own.
Float32List searchEmbed({required String text}) =>
    RustLib.instance.api.crateApiSearchSearchEmbed(text: text);

/// Dimensionality of the embedding vectors produced by [`search_embed`].
int searchEmbedDims() => RustLib.instance.api.crateApiSearchSearchEmbedDims();

/// A candidate near-duplicate pair (Dart DTO).
class DuplicatePairDto {
  final String a;
  final String b;

  /// Estimated Jaccard similarity in `[0, 1]`.
  final double similarity;

  const DuplicatePairDto({
    required this.a,
    required this.b,
    required this.similarity,
  });

  @override
  int get hashCode => a.hashCode ^ b.hashCode ^ similarity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DuplicatePairDto &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          similarity == other.similarity;
}

/// A single search result (Dart DTO).
class SearchHitDto {
  final String documentId;
  final double score;
  final String? snippet;

  const SearchHitDto({
    required this.documentId,
    required this.score,
    this.snippet,
  });

  @override
  int get hashCode => documentId.hashCode ^ score.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHitDto &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          score == other.score &&
          snippet == other.snippet;
}
