// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain.dart';
import '../frb_generated.dart';
import '../storage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_ms`, `record_user_feedback`, `set_tags_internal`, `store`, `update_title_internal`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Open (or create) a document repository rooted at `root` on disk.
Future<DocumentRepository> openRepository({required String root}) =>
    RustLib.instance.api.crateApiStorageOpenRepository(root: root);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocumentRepository>>
abstract class DocumentRepository implements RustOpaqueInterface {
  /// Apply a tag set WITHOUT stamping `tags_manual` (used by suggestion
  /// auto-apply: a suggestion is not a *user* manual edit, so we do not want
  /// it to influence the "user-authored" learning weight).
  Future<void> applySuggestedTags({
    required String documentId,
    required List<String> tags,
  });

  /// Apply a suggested title WITHOUT stamping `title_manual`.
  Future<void> applySuggestedTitle({
    required String documentId,
    required String title,
  });

  Future<void> assignPath({required PathAssignment assignment});

  Future<List<String>> children({required String parent});

  /// Wipe all learning data.
  Future<void> clearFeedback();

  /// Delete a document and (when unreferenced) its blob.
  Future<void> delete({required String id});

  Future<void> deleteContent({required String documentId});

  /// Remove all suggestion rows for a document.
  Future<void> deleteDocumentSuggestions({required String documentId});

  Future<void> deletePath({required String path});

  Future<List<String>> documentsAt({required String path});

  /// Aggregated accept/reject evidence per term (feedback model input).
  Future<Map<String, FeedbackStats>> feedbackStats({
    SuggestionKind? kind,
    String? context,
  });

  /// Fetch a document's metadata.
  Future<Document> get_({required String id});

  Future<Content?> getContent({required String documentId});

  Future<void> link({required HierarchyLink link});

  Future<List<HierarchyPath>> listPaths();

  Future<List<Tag>> listTags();

  /// Update the review status (pending/applied/dismissed) of one suggestion.
  Future<void> markSuggestion({
    required String suggestionId,
    required SuggestionStatus status,
  });

  Future<List<HierarchyPath>> pathsOf({required String documentId});

  /// Housekeeping: drop non-pending suggestions older than `older_than_ms`.
  Future<void> pruneSuggestions({required PlatformInt64 olderThanMs});

  /// Insert or replace a document and its raw bytes.
  Future<void> put({required Document doc, required List<int> bytes});

  Future<void> putContent({
    required String documentId,
    required String text,
    required String source,
  });

  Future<void> putPath({required String path});

  /// Persist (or update) one pending suggestion row.
  Future<void> putSuggestion({required DocumentSuggestion suggestion});

  Future<void> putTag({required Tag tag});

  /// List documents matching a query.
  Future<List<Document>> query({required DocumentQuery query});

  /// Fetch a document's raw bytes.
  Future<Uint8List> readBytes({required String id});

  /// Persist one feedback event.
  Future<void> recordFeedback({required SuggestionFeedback feedback});

  /// Replace the full tag set on a document (creating tag-catalog entries as
  /// needed) so the UI can add/remove tags without re-putting raw bytes.
  ///
  /// This is a *user* tag edit, so the persisted `extra` map is marked with
  /// `tags_manual = "true"`. Bulk auto-organization therefore preserves the
  /// user's assignment instead of clobbering it.
  Future<void> setTags({
    required String documentId,
    required List<String> tags,
  });

  /// Fetch a document's suggestions (optionally filtered by kind), newest
  /// alternatives first per kind.
  Future<List<DocumentSuggestion>> suggestionsOf({
    required String documentId,
    SuggestionKind? kind,
  });

  Future<void> unassignPath({required String documentId, required String path});

  /// Rename a document through the repository (`repo.put`, reusing the stored
  /// raw bytes so the rename never depends on re-ingestion).
  ///
  /// This is a *user* rename, so the persisted `extra` map is marked with
  /// `title_manual = "true"`. Bulk auto-organization therefore preserves the
  /// user's title instead of clobbering it.
  Future<void> updateTitle({required String documentId, required String title});
}
