// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`, `to_conflict_dto`, `to_conflict_kind_dto`, `to_event_dto`, `to_phase_dto`, `to_resolution_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Start the sync engine and emit a `Started` event.
void syncStart() => RustLib.instance.api.crateApiSyncSyncStart();

/// The peer ids the engine is currently connected to.
List<String> syncPeers() => RustLib.instance.api.crateApiSyncSyncPeers();

/// Register a peer the engine should try to sync with.
void syncConnect({required String peerId}) =>
    RustLib.instance.api.crateApiSyncSyncConnect(peerId: peerId);

/// Replicate a single document (and its bytes) to all connected peers.
void syncPush({required String documentId}) =>
    RustLib.instance.api.crateApiSyncSyncPush(documentId: documentId);

/// Pull remote changes from all connected peers and reconcile them. Returns the
/// per-document conflict resolutions from this round.
List<SyncResolutionDto> syncPull() =>
    RustLib.instance.api.crateApiSyncSyncPull();

/// Conflicts currently awaiting manual resolution.
List<SyncConflictDto> syncConflicts() =>
    RustLib.instance.api.crateApiSyncSyncConflicts();

/// Open a Dart `Stream` of sync events (progress, transfers, conflicts, done).
///
/// The returned stream stays open until the Dart side closes it, receiving one
/// [`SyncEventDto`] per engine event.
Stream<SyncEventDto> syncEvents() =>
    RustLib.instance.api.crateApiSyncSyncEvents();

/// A record of a conflict awaiting manual resolution, as a plain struct.
class SyncConflictDto {
  final String documentId;
  final SyncConflictKindDto kind;
  final String localChecksum;
  final String remoteChecksum;
  final PlatformInt64 localUpdatedAtMs;
  final PlatformInt64 remoteUpdatedAtMs;
  final String? forkedDocumentId;

  /// `"local"`, `"remote"`, or `"fork"`.
  final String winner;

  const SyncConflictDto({
    required this.documentId,
    required this.kind,
    required this.localChecksum,
    required this.remoteChecksum,
    required this.localUpdatedAtMs,
    required this.remoteUpdatedAtMs,
    this.forkedDocumentId,
    required this.winner,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      kind.hashCode ^
      localChecksum.hashCode ^
      remoteChecksum.hashCode ^
      localUpdatedAtMs.hashCode ^
      remoteUpdatedAtMs.hashCode ^
      forkedDocumentId.hashCode ^
      winner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConflictDto &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          kind == other.kind &&
          localChecksum == other.localChecksum &&
          remoteChecksum == other.remoteChecksum &&
          localUpdatedAtMs == other.localUpdatedAtMs &&
          remoteUpdatedAtMs == other.remoteUpdatedAtMs &&
          forkedDocumentId == other.forkedDocumentId &&
          winner == other.winner;
}

/// The kind of a conflict (plain enum; no Freezed needed).
enum SyncConflictKindDto { contentDiverged, metadataDiverged }

/// A sync event delivered to Dart over the [`sync_events`] stream.
class SyncEventDto {
  final SyncEventKindDto kind;
  final String peerId;

  /// Populated for [`SyncEventKindDto::Progress`].
  final SyncPhaseDto? phase;

  /// Populated for [`SyncEventKindDto::DocumentTransferred`].
  final String? documentId;
  final BigInt? bytes;

  /// Populated for [`SyncEventKindDto::Conflict`].
  final SyncConflictDto? conflict;

  /// Populated for [`SyncEventKindDto::Finished`].
  final List<SyncResolutionDto> results;

  const SyncEventDto({
    required this.kind,
    required this.peerId,
    this.phase,
    this.documentId,
    this.bytes,
    this.conflict,
    required this.results,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      peerId.hashCode ^
      phase.hashCode ^
      documentId.hashCode ^
      bytes.hashCode ^
      conflict.hashCode ^
      results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          peerId == other.peerId &&
          phase == other.phase &&
          documentId == other.documentId &&
          bytes == other.bytes &&
          conflict == other.conflict &&
          results == other.results;
}

/// The kind of a sync event (enum of unit variants; no Freezed needed).
enum SyncEventKindDto {
  started,
  progress,
  documentTransferred,
  conflict,
  finished,
}

/// Coarse-grained sync phase reported in progress events.
enum SyncPhaseDto {
  exchangingManifests,
  transferringContent,
  reconciling,
  done,
}

/// A single document-conflict outcome, as a plain struct over the bridge.
class SyncResolutionDto {
  /// `"merged"`, `"remoteWon"`, `"localWon"`, or `"forked"`.
  final String kind;

  /// For `"forked"`, the id of the created fork.
  final String? documentId;

  const SyncResolutionDto({required this.kind, this.documentId});

  @override
  int get hashCode => kind.hashCode ^ documentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResolutionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          documentId == other.documentId;
}
