// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'feedback.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rules.dart';

/// Where a suggested title came from.
enum FilenameSource {
  /// Deterministic template over keywords/metadata.
  template,

  /// Generated by a generative LLM (only when a provider is enabled).
  generative,
}

/// Global auto-organization settings.
class OrgConfig {
  /// Whether to run the deterministic classic-ML pipeline at all.
  final bool enabled;

  /// Whether the generative LLM filename tier is allowed. Requires an AI
  /// provider to be configured; ignored (and forced offline) when disabled.
  final bool generativeEnabled;

  /// Similarity threshold (Jaccard) above which a document is a duplicate.
  final double dedupThreshold;

  /// Shingle size for MinHash de-duplication.
  final BigInt shingleK;

  /// Number of clusters for k-means (overridden by `default_k` when 0).
  final BigInt clusterK;

  /// Placement rules + filename template.
  final RuleSet rules;

  /// On-device feedback learning: `Off` (no recording/re-ranking) or `Basic`
  /// (per-term preference model). A future `Advanced` classifier plugs into
  /// the same enum behind the settings surface.
  final LearningMode learningMode;

  const OrgConfig({
    required this.enabled,
    required this.generativeEnabled,
    required this.dedupThreshold,
    required this.shingleK,
    required this.clusterK,
    required this.rules,
    required this.learningMode,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      generativeEnabled.hashCode ^
      dedupThreshold.hashCode ^
      shingleK.hashCode ^
      clusterK.hashCode ^
      rules.hashCode ^
      learningMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrgConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          generativeEnabled == other.generativeEnabled &&
          dedupThreshold == other.dedupThreshold &&
          shingleK == other.shingleK &&
          clusterK == other.clusterK &&
          rules == other.rules &&
          learningMode == other.learningMode;
}

/// The result of organizing a single document: everything the caller needs to
/// apply (or show for approval).
class OrgPlan {
  final String documentId;

  /// Predicted tags (emergent + reused), ordered by confidence. This is the
  /// rank-0 tag set: what auto-apply writes when the user has not manually
  /// tagged the document.
  final List<String> tags;

  /// Alternative tag sets (rank >= 1) the review UI can offer, ordered by
  /// preference-model score when learning is on.
  final List<List<String>> altTagSets;

  /// Deterministically resolved hierarchy path, if any.
  final String? suggestedPath;

  /// Renamed filename (title), if the pipeline produced one. Rank-0 title.
  final String? suggestedTitle;

  /// Alternative titles (rank >= 1).
  final List<String> altTitles;

  /// Id of an existing document this one is a duplicate of, if any.
  final String? isDuplicateOf;

  /// Aggregate confidence in `[0, 1]`.
  final double confidence;

  /// Whether the filename came from a generative provider vs. a template.
  final FilenameSource filenameSource;

  const OrgPlan({
    required this.documentId,
    required this.tags,
    required this.altTagSets,
    this.suggestedPath,
    this.suggestedTitle,
    required this.altTitles,
    this.isDuplicateOf,
    required this.confidence,
    required this.filenameSource,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      tags.hashCode ^
      altTagSets.hashCode ^
      suggestedPath.hashCode ^
      suggestedTitle.hashCode ^
      altTitles.hashCode ^
      isDuplicateOf.hashCode ^
      confidence.hashCode ^
      filenameSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrgPlan &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          tags == other.tags &&
          altTagSets == other.altTagSets &&
          suggestedPath == other.suggestedPath &&
          suggestedTitle == other.suggestedTitle &&
          altTitles == other.altTitles &&
          isDuplicateOf == other.isDuplicateOf &&
          confidence == other.confidence &&
          filenameSource == other.filenameSource;
}
