// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Per-suggestion-type learning toggle.
enum LearningMode {
  /// Do not record feedback and do not re-rank suggestions.
  off,

  /// Feedback-weighted per-term preference model (default).
  basic,
}
