// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The template configuration used when generating filenames.
class RuleSet {
  /// Supported placeholders: `{keywords}`, `{tags}`, `{title}`, `{date}`, `{ext}`.
  final String filenameTemplate;

  const RuleSet({required this.filenameTemplate});

  @override
  int get hashCode => filenameTemplate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleSet &&
          runtimeType == other.runtimeType &&
          filenameTemplate == other.filenameTemplate;
}
